# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0002_auto_20160413_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='rated_by',
        ),
        migrations.RemoveField(
            model_name='users',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='users',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='chat_history',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 16, 48, 20, 460821)),
        ),
    ]
