# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 05:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0003_auto_20160415_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reporter_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='transact_status',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='chat_history',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 15, 5, 4, 15, 117525)),
        ),
    ]
