# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0003_auto_20160413_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='reported_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='verification_code',
            field=models.CharField(default='asdfghjkl', max_length=1000),
        ),
        migrations.AlterField(
            model_name='chat_history',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 16, 49, 2, 615939)),
        ),
    ]
