# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0004_auto_20160415_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_history',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 15, 5, 5, 34, 651241)),
        ),
    ]
