# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0006_auto_20160415_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_history',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 15, 7, 29, 4, 402663)),
        ),
    ]
