# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0007_auto_20160415_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='seeker',
        ),
        migrations.AlterField(
            model_name='chat_history',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 15, 7, 39, 19, 685025)),
        ),
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
