# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0009_auto_20160329_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rating',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
