# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0010_users_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image_url',
            field=models.URLField(default=0),
        ),
    ]
