# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0013_auto_20160406_1918'),
        ('splitnsave', '0011_users_image_url'),
    ]

    operations = [
    ]
