# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import splitnsave.models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0014_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_list',
            name='city_id',
            field=models.IntegerField(default=splitnsave.models.city_number, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profession_list',
            name='profession_name',
            field=models.CharField(choices=[('', ''), ('Student', 'Student'), ('abc', 'abc')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='verification_link',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
