# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0015_auto_20160406_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True),
        ),
    ]
