# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import splitnsave.models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0016_auto_20160406_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_history',
            name='id',
        ),
        migrations.AddField(
            model_name='products',
            name='confirm_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='splitnsave.transaction_ratings'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.IntegerField(default=splitnsave.models.product_number, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='poster', to='splitnsave.users'),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='splitnsave.products'),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='seeker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seeker', to='splitnsave.users'),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='transact_status',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
