# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0017_auto_20160409_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
