# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0018_auto_20160409_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_ratings',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
