# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0019_auto_20160409_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='post_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='confirm_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_interested',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitnsave.products'),
        ),
        migrations.AddField(
            model_name='user_interested',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitnsave.users'),
        ),
    ]
