# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0022_auto_20160410_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='post_date',
        ),
    ]
