# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitnsave', '0024_products_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='confirm_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
