from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(users)
admin.site.register(city_list)
admin.site.register(institute_list)
admin.site.register(profession_list)
admin.site.register(chat_history)
admin.site.register(categories)
admin.site.register(products)
admin.site.register(transaction_history)
admin.site.register(transaction_ratings)
admin.site.register(post_reporting)
admin.site.register(user_reporting)
admin.site.register(car_service_list)
admin.site.register(car_name_list)
admin.site.register(car_type_list)
admin.site.register(cabs)
admin.site.register(laundary)
admin.site.register(sub_category_list)
admin.site.register(keyword_list)
admin.site.register(equipment)
admin.site.register(apartments)
admin.site.register(tag_list)
admin.site.register(books)
admin.site.register(user_interested)
admin.site.register(user_report_post)
admin.site.register(user_report_user)
admin.site.register(notifications)